ActivelyServedPizza/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ActivelyServedPizza.Models;
using ActivelyServedPizza.Models.OrderViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;
using PizzaSharp.Interfaces;
using PizzaSharp.Models;

namespace ActivelyServedPizza.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IOrderRepository _orderRepository;
        private readonly IPizzaRepository _pizzaRepository;
        private readonly IItemRepository _itemRepository;

        public CartController(UserManager<ApplicationUser> userManager, 
            IOrderRepository orderRepository, IPizzaRepository pizzaRepository, IItemRepository itemRepository)
        {
            _userManager = userManager;
            _orderRepository = orderRepository;
            _pizzaRepository = pizzaRepository;
            _itemRepository = itemRepository;
        }


        public async Task<IActionResult> Index()
        {
            Order order = await GetOrder();            
            return View(order);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Order updatedOrder)
        {
            Order order = await GetOrder();

            order.Delivery = updatedOrder.Delivery;
            order.DeliveryAddress = updatedOrder.DeliveryAddress;
            order.DeliveryMessage = updatedOrder.DeliveryMessage;

            AddOrder(order);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> PlaceOrder()
        {
            Order order = await GetOrder();

            int n = order.Items.Count;
            for (int i = 0; i < n; ++i)
            {
                order.Items[i].Product = _pizzaRepository.Get(order.Items[i].Product.ProductId);
            }

            _orderRepository.Add(order);
            HttpContext.Session.Remove("cart");

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> AddToOrder(OrderViewModel orderModel)
        {
            Order order = await GetOrder();

            Pizza pizza = _pizzaRepository.Get(Guid.Parse(orderModel.PizzaId));

            Item item = new Item();
            item.Amount = orderModel.Amount;
            item.ItemId = Guid.NewGuid();
            item.Product = pizza;
            item.Size = orderModel.Size;

            order.Items.Add(item);

            AddOrder(order);

            return RedirectToAction("Index");
        }

        private void AddOrder(Order order)
        {
            var orderString = JsonConvert.SerializeObject(order);
            HttpContext.Session.SetString("cart", orderString);
        }

        private async Task<Order> GetOrder()
        {
            var sessionString = HttpContext.Session.GetString("cart");

            Order order;
            if (sessionString == null)
            {
                var currentUser = _userManager.GetUserAsync(HttpContext.User);
                order = new Order();
                order.OrderId = Guid.NewGuid();
                order.DateCreated = DateTime.Now;
                order.DeliveryDate = DateTime.Now;
                order.DeliveryAddress = "";
                order.Items = new List<Item>();
                order.User = Guid.Parse((await currentUser).Id);
            }
            else
            {
                order = JsonConvert.DeserializeObject<Order>(sessionString, new ProductConverter());
            }

            return order;
        }

        public async Task<IActionResult> AllOrders(Guid userId)
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            bool isAdmin = await _userManager.IsInRoleAsync(currentUser, Roles.Admin);

            List<Order> list = _orderRepository
                .GetAll(Guid.Parse(currentUser.Id), isAdmin)
                .ToList();

            return View(list);
        }
    }
}

ActivelyServedPizza/Controllers/PizzaController.cs
using ActivelyServedPizza.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PizzaSharp.Interfaces;
using PizzaSharp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ActivelyServedPizza.Models.OrderViewModels;

namespace ActivelyServedPizza.Controllers
{
    [Authorize]
    public class PizzaController : Controller
    {
        private readonly IPizzaRepository _repository;
        private readonly UserManager<ApplicationUser> _userManager;
        // Inject user manager into constructor
        public PizzaController(IPizzaRepository repository, UserManager<ApplicationUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        public async Task<IActionResult> Offer()
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            bool isAdmin = await _userManager.IsInRoleAsync(currentUser, Roles.Admin);

            List<Pizza> list = _repository
                .GetAll(Guid.Parse(currentUser.Id), isAdmin)
                .OrderBy(p => p.IsCreatedByAdmin)
                .ToList();

            ApplicationUser userX = await _userManager.FindByIdAsync(currentUser.Id);

            return View(list);
        }


        public IActionResult Show(Guid pizzaId)
        {
            Pizza pizza = _repository.Get(pizzaId);

            OrderViewModel model = new OrderViewModel();
            model.Pizza = pizza;

            return View(model);
        }
    }
}

ActivelyServedPizza/Views/Pizza/Offer.cshtml
@model List<PizzaSharp.Models.Pizza>

@{
    ViewData["Title"] = "Ponuda";
}

<head>
    <!-- Custom CSS -->
    <link href="~/css/shop-homepage.css" rel="stylesheet">
</head>

<!-- Page Content -->
<div class="row">

    <div class="col-md-10 col-md-offset-1">

        <div class="row">
            @foreach (var pizza in Model)
            {
                @Html.Partial("PizzaView", pizza)
            }
        </div>

    </div>

</div>

ActivelyServedPizza/Views/Pizza/PizzaView.cshtml
@using PizzaSharp.Models
@model PizzaSharp.Models.Pizza

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="~/images/pizza/@Model.PhotoName" alt="">
        <div class="caption">
            <h4 class="pull-right">@Model.PriceMedium kn<sup>*</sup></h4>
            <h4>
                <a asp-controller="Pizza" 
                   asp-action="Show" 
                   asp-route-pizzaId="@Model.ProductId">@Model.Name</a>
            </h4>
            <p>
                Sastojci:
                <br />
                
                @{bool isFirst = true;}
                @foreach (var ingredient in Model.Ingredients)
                {
                    if (!isFirst)
                    {
                        <span>, @ingredient.Name</span>
                    }
                    else
                    {
                        <span>@ingredient.Name</span>
                        isFirst = false;
                    }
                }
            </p>
        </div>
        <div class="ratings">
            <p class="pull-right">Komentari(@Model.CommentCount())</p>
            <p>    
                @for (int i = 0; i < Model.GetRating(); i++)
                {
                    <span class="glyphicon glyphicon-star"></span>
                }

                @for (int i = 5 - Model.GetRating(); i > 0; i--)
                {
                    <span class="glyphicon glyphicon-star-empty"></span>
                }
            </p>
        </div>

    </div>
</div>

ActivelyServedPizza/Views/Pizza/Show.cshtml
@using ActivelyServedPizza.Models.OrderViewModels
@model OrderViewModel

@{
ViewData["Title"] = "Pizza details";
}

<link href="~/css/shop-item.css" rel="stylesheet">


<!-- Page Content -->
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="thumbnail">
            <img class="img-responsive" src="~/images/pizza/@Model.Pizza.PhotoName" alt="" style="height:300px">
            <div class="caption-full">
                <form method="post" asp-controller="Cart" asp-action="AddToOrder" asp-area="">
                    <div class="row">
                        <input type="hidden" asp-for="@Model.PizzaId" value="@Model.Pizza.ProductId" />
                        <div class="col-md-5">
                            <h2 class="pull-left">@Model.Pizza.Name</h2>
                        </div>
                        <div class="col-md-2">
                            <select asp-for="@Model.Size" class="form-control">
                                <option value="1">Mala</option>
                                <option value="2">Srednja</option>
                                <option value="3">Velika</option>
                            </select>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group">
                                <span class="input-group-addon" id="sizing-addon1">Količina</span>
                                <input asp-for="@Model.Amount" type="number" min="1" max="25" step="1" class="form-control" placeholder="1" aria-describedby="sizing-addon2">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="text-right">
                                <input type="submit" class="btn btn-success btn-block" value="Dodaj">
                            </div>
                        </div>
                    </div>
                </form>
                <div class="row" style="padding-left:15px">

                    <div class="col-md-3">
                        <h4 class="pull-left">
                            Cijena male: @Model.Pizza.PriceSmall kn <br />
                            Cijena srednje: @Model.Pizza.PriceMedium kn <br />
                            Cijena velike: @Model.Pizza.PriceBig kn <br />
                            <br />

                            Sastojci: <br />
                                                  
                            <p>
                                @{bool isFirst = true;}
                                @foreach (var ingredient in Model.Pizza.Ingredients)
                                {
                                    if (!isFirst)
                                    {
                                        <span>, @ingredient.Name</span>
                                    }
                                    else
                                    {
                                        <span>@ingredient.Name</span>
                                        isFirst = false;
                                    }
                                }
                            </p>

                        </h4>
                        
                    </div>

                </div>


             
            </div>
            <div class="ratings">
                <p class="pull-right">Komentari(@Model.Pizza.CommentCount())</p>
                <p>
                    @for (int i = 0; i < Model.Pizza.GetRating(); i++)
                    {
                        <span class="glyphicon glyphicon-star"></span>
                    }

                    @for (int i = 5 - Model.Pizza.GetRating(); i > 0; i--)
                    {
                        <span class="glyphicon glyphicon-star-empty"></span>
                    }
                    @Model.Pizza.GetRating()  
                </p>
            </div>
        </div>
        <div class="well">
            <div class="row">
                <div class="col-md-2 col-md-offset-10">
                    <div class="text-right">
                        <a class="btn btn-success btn-block">Komentiraj</a>
                    </div>
                    <div class="text-right">
                        <a class="btn btn-success btn-block">Ocijeni</a>
                    </div>
                    <div>
                        @if (@Model.Pizza.CommentCount() != 0)
                        {
                            @foreach (var comment in Model.Pizza.Comments)
                            {
                                @Html.Partial("../Comment/CommentShow", comment)
                            }
                        }
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>